// Test generated by RoostGPT for test Java-Test using AI Type Open AI and AI Model gpt-4

package com.mkyong.examples;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

public class MagicBuilder_getLucky_70e28fb599_Test {

    @Test
    public void testGetLucky_success() {
        int expectedValue = 7;
        int actualValue = MagicBuilder.getLucky();
        assertEquals(expectedValue, actualValue);
    }

    @Test
    public void testGetLucky_failure() {
        int unexpectedValue = 8;
        int actualValue = MagicBuilder.getLucky();
        assertNotEquals(unexpectedValue, actualValue);
    }

    @Test
    public void testGetLucky_zero() {
        int zeroValue = 0;
        int actualValue = MagicBuilder.getLucky();
        assertNotEquals(zeroValue, actualValue);
    }

    @Test
    public void testGetLucky_negative() {
        int negativeValue = -1;
        int actualValue = MagicBuilder.getLucky();
        assertNotEquals(negativeValue, actualValue);
    }
}
