// Test generated by RoostGPT for test Java-Test using AI Type Open AI and AI Model gpt-4

package com.mkyong.examples;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

public class MessageBuilder_getHelloWorld_0c11dcfccb_Test {

    @Test
    public void testGetHelloWorld() {
        String expectedOutput = "hello world";
        String actualOutput = MessageBuilder.getHelloWorld();
        assertEquals(expectedOutput, actualOutput, "The actual output did not match the expected output");
    }

    @Test
    public void testGetHelloWorldFailure() {
        String unexpectedOutput = "hello universe";
        String actualOutput = MessageBuilder.getHelloWorld();
        assertNotEquals(unexpectedOutput, actualOutput, "The actual output matched the unexpected output");
    }

    @Test
    public void testGetHelloWorldNotNull() {
        String actualOutput = MessageBuilder.getHelloWorld();
        assertNotNull(actualOutput, "The actual output should not be null");
    }

    @Test
    public void testGetHelloWorldLength() {
        int expectedLength = 11;
        String actualOutput = MessageBuilder.getHelloWorld();
        assertEquals(expectedLength, actualOutput.length(), "The length of the actual output did not match the expected length");
    }
}
