// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package com.mkyong.examples;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class MessageBuilder_getNumber10_e685fe5716_Test {

    @Test
    public void testGetNumber10_Success() {
        int result = MessageBuilder.getNumber10();
        Assertions.assertEquals(10, result, "The method should return 10");
    }

    @Test
    public void testGetNumber10_Failure() {
        int result = MessageBuilder.getNumber10();
        Assertions.assertNotEquals(9, result, "The method should not return 9");
    }
}
